export const jobTeams = [
  "All teams",
  "Technology",
  "Cabin Crew",
  "Operation",
  "Customer Service",
  "Marketing",
  "Finance",
];

export const jobLocations = [
  "All locations",
  "Damascus, Syria",
  "Abu Dhabi, UAE",
  "Dubai, UAE",
  "Riyadh, Saudi Arabia",
];

export const jobExperienceLevels = [
  "All experience levels",
  "Internship",
  "Junior",
  "Mid-level",
  "Senior",
  "Lead",
];

export const jobsList = [
  {
    id: "250003D",
    title: "Junior Frontend Developer",
    team: "Technology",
    experienceLevel: "Junior",
    location: "Damascus, Syria",
    postedAgo: "2 days ago",
    closingDate: "05-12-2025",
    employmentType: "Full time",
    dep: "Technology",
    level: "Junior",
  },
  {
    id: "250004D",
    title: "Senior Backend Developer",
    team: "Technology",
    experienceLevel: "Senior",
    location: "Damascus, Syria",
    postedAgo: "2 days ago",
    closingDate: "05-12-2025",
    employmentType: "Full time",
    dep: "Technology",
    level: "Senior",
  },
  {
    id: "250006C",
    title: "Lead Mobile Developer",
    team: "Technology",
    experienceLevel: "Lead",
    location: "Damascus, Syria",
    postedAgo: "4 days ago",
    closingDate: "05-01-2026",
    employmentType: "Full time",
    dep: "Marketing",
    level: "Lead",
  },
  {
    id: "250004A",
    title: "Data Analyst",
    team: "Operation",
    experienceLevel: "Mid-level",
    location: "Damascus, Syria",
    postedAgo: "15 days ago",
    closingDate: "05-11-2025",
    employmentType: "Full time",
    dep: "Operation",
    level: "Mid-level",
  },
  {
    id: "250005B",
    title: "Digital Marketing Internship",
    team: "Marketing",
    experienceLevel: "Internship",
    location: "Damascus, Syria",
    postedAgo: "4 days ago",
    closingDate: "05-01-2026",
    employmentType: "Full time",
    dep: "Marketing",
    level: "Internship",
  },
  {
    id: "250002E",
    title: "Graphic Designer",
    team: "Marketing",
    experienceLevel: "Mid-level",
    location: "Damascus, Syria",
    postedAgo: "4 days ago",
    closingDate: "05-01-2026",
    employmentType: "Part time",
    dep: "Marketing",
    level: "Mid-level",
  },
];

export const saveJobs = [
  {
    id: "250003D",
    title: "Junior Frontend Developer",
    team: "Technology",
    experienceLevel: "Junior",
    location: "Damascus, Syria",
    postedAgo: "2 days ago",
    closingDate: "05-12-2025",
    employmentType: "Full time",
    tags: ["Technology", "Junior"],
  },
  {
    id: "250004D",
    title: "Senior Backend Developer",
    team: "Technology",
    experienceLevel: "Senior",
    location: "Damascus, Syria",
    postedAgo: "2 days ago",
    closingDate: "05-12-2025",
    employmentType: "Full time",
    tags: ["Technology", "Senior"],
  },
];
