export const vacancies = [
  {
    title: "Junior Frontend Developer",
    category: "Technology",
    level: "Junior",
    id: "2500002C",
    closingDate: "15-12-2025",
    type: "Part time",
    posted: "1 week ago",
    location: "Damascus, Syria",
  },
  {
    title: "Senior Backend Developer",
    category: "Technology",
    level: "Senior",
    id: "250001B",
    closingDate: "30-11-2025",
    type: "Full time",
    posted: "2 days ago",
    location: "Damascus, Syria",
  },
  {
    title: "Data Analyst",
    category: "Operations",
    level: "Mid-level",
    id: "2500030D",
    closingDate: "05-01-2026",
    type: "Contract",
    posted: "3 days ago",
    location: "Damascus, Syria",
  },
  {
    title: "Digital Marketing Intern",
    category: "Marketing",
    level: "Intern",
    id: "250004E",
    closingDate: "20-01-2026",
    type: "Internship",
    posted: "5 days ago",
    location: "Damascus, Syria",
  },
];
